on:
  workflow_dispatch:
jobs:
  scala-steward:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: sbt/setup-sbt@v1.1.1
    - uses: scala-steward-org/scala-steward-action@v2.70.0
